// Vectors from PyNaCl (test/vectors.json, generated by aamio-listen's crypto)
// prove the two implementations agree byte for byte. The second test runs two
// agents against the public service, so it needs the network.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  Aamio, AamioError, Keys, sha256hex, deriveAddress, curvePublic, hex, unhex, hashPrefix,
  threadSigningInput, receiptRoot, verify, isEnvelope,
} from "../src/aamio.js";

const vectors = JSON.parse(readFileSync(new URL("./vectors.json", import.meta.url), "utf-8"));
const decoder = new TextDecoder();

test("agrees with PyNaCl and the server, byte for byte", () => {
  assert.equal(sha256hex("abc"), vectors.sha256_abc);
  assert.equal(deriveAddress(vectors.id), vectors.w);

  const a = Keys.fromSeedHex(vectors.a.seed);
  const b = Keys.fromSeedHex(vectors.b.seed);
  assert.equal(a.public, vectors.a.public);
  assert.equal(a.hash, vectors.a.hash);
  assert.equal(hex(curvePublic(a.public)), vectors.a.curvePublic);
  assert.equal(hex(curvePublic(b.public)), vectors.b.curvePublic);

  assert.equal(threadSigningInput(vectors.w, vectors.body), vectors.signInput);
  assert.equal(a.sign(vectors.signInput), vectors.signature);
  assert.ok(verify(a.public, vectors.signInput, vectors.signature));
  assert.ok(!verify(b.public, vectors.signInput, vectors.signature));

  assert.ok(isEnvelope(vectors.envelopeFromAToB));
  assert.equal(JSON.parse(vectors.envelopeFromAToB).to, hashPrefix(b.public));
  assert.equal(decoder.decode(b.open(a.public, vectors.envelopeFromAToB)), vectors.plaintext);
  // The sender can always open its own box, both sides derive the same key. A third party cannot.
  assert.throws(() => Keys.generate().open(a.public, vectors.envelopeFromAToB));

  const sealed = b.seal(a.public, "hello from javascript");
  assert.equal(decoder.decode(a.open(b.public, sealed)), "hello from javascript");

  assert.equal(receiptRoot(vectors.receipt), vectors.receipt.root);
  assert.equal(unhex(hex(a.seed)).join(","), a.seed.join(","));
});

test("two agents on aamio.at: allowlist, signed and encrypted exchange, presence, receipt", async () => {
  const one = new Aamio({ keys: Keys.generate() });
  const two = new Aamio({ keys: Keys.generate() });

  const inboxOne = await one.open({ ttl: 120, allow: [two.keys.public] });
  const inboxTwo = await two.open({ ttl: 120, allow: [one.keys.public] });
  assert.equal(inboxOne.w, deriveAddress(inboxOne.id));
  assert.deepEqual(inboxOne.allow, [two.keys.public]);

  await one.presence.publish({ w: inboxOne.w, tags: ["test"], ttl: 30 });
  assert.equal(await two.presence.find(one.keys.public), inboxOne.w);
  assert.equal(await two.presence.find(two.keys.public), null);

  const stranger = new Aamio();
  await assert.rejects(stranger.send(inboxOne.w, { text: "spam" }), (error) => error instanceof AamioError && error.status === 403);

  const sent = await two.send(inboxOne.w, { text: "Send me the log for ARC-4471", reply_to: inboxTwo.w }, { encryptTo: one.keys.public });
  assert.equal(sent.seq, 1);
  assert.equal(sent.verified, true);

  const got = await one.read(inboxOne, { wait: 5 });
  assert.equal(got.messages.length, 1);
  const message = got.messages[0];
  assert.equal(message.encrypted, true);
  assert.equal(message.verified, true);
  assert.equal(message.from, two.keys.public);
  assert.equal(message.json.reply_to, inboxTwo.w);
  assert.equal(message.error, undefined);

  await one.send(message.json.reply_to, "Log ARC-4471: no excursion", { encryptTo: two.keys.public });
  const controller = new AbortController();
  let answer = null;
  for await (const m of two.listen(inboxTwo, { wait: 5, signal: controller.signal })) {
    answer = m;
    controller.abort();
    break;
  }
  assert.equal(answer.plain, "Log ARC-4471: no excursion");
  assert.equal(answer.from, one.keys.public);

  const receipt = await one.receipt(inboxOne);
  assert.equal(receipt.matches, true);
  assert.equal(receipt.receipt.count, 1);
  assert.equal(receipt.commitment, "sha256:" + receipt.root);
  assert.deepEqual(receipt.receipt.keys, [two.keys.public]);

  await one.presence.withdraw();
  assert.equal(await one.presence.get(one.keys.public), null);
  assert.deepEqual(await one.close(inboxOne), { w: inboxOne.w, deleted: true });
  await two.close(inboxTwo);
  const gone = await one.read(inboxOne);
  assert.equal(gone.exists, false);
});

test("the board: post, find by parent tag, answer sealed, move to a private thread", async () => {
  const poster = new Aamio({ keys: Keys.generate() });
  const answerer = new Aamio({ keys: Keys.generate() });

  const { post, inbox } = await poster.board.post(
    { kind: "need", title: "Temperature log for ARC-4471", text: "The full cold chain log, as JSON.", tags: ["test.board", "coldchain"], lang: "en", ttl: 120 },
  );
  assert.equal(inbox.allow[0], "*");            // the reply inbox takes strangers, signed only
  assert.equal(post.w, inbox.w);
  assert.equal(post.lang, "en");

  const page = await answerer.board.find({ kind: "need", tags: ["test"], after: 0 });
  const found = page.posts.find((p) => p.id === post.id);
  assert.ok(found, "a tag covers its dotted children");
  assert.equal(page.next >= post.seq, true);
  assert.equal((await answerer.board.find({ tags: ["test.boar"] })).posts.some((p) => p.id === post.id), false);

  const answer = await answerer.board.answer(found, { text: "I have it", ref: "ARC-4471" });
  assert.equal(answer.verified, true);

  const got = await poster.read(inbox, { wait: 5 });
  const replies = poster.board.replies(got.messages, post.id);
  assert.equal(replies.length, 1);
  assert.equal(replies[0].encrypted, true);
  assert.equal(replies[0].from, answerer.keys.public);
  assert.equal(replies[0].json.text, "I have it");

  const channel = await poster.openWith(answerer.keys.public, { ttl: 120, replyTo: replies[0].json.reply_to, note: "moving here" });
  assert.deepEqual(channel.allow, [answerer.keys.public]);
  const handed = await answerer.read(answer.inbox, { wait: 5 });
  assert.equal(handed.messages[0].json.channel, channel.w);

  const tree = await poster.board.tags();
  const branch = tree.tags.find((t) => t.tag === "test");
  assert.ok(branch && branch.live >= 1 && branch.children.some((c) => c.tag === "test.board"));

  await poster.board.withdraw(post.id);
  assert.equal(await poster.board.get(post.id), null);
  await Promise.all([poster.close(inbox), answerer.close(answer.inbox), poster.close(channel)]);
});
